ct_core_home:
    path:     /
    defaults: { _controller: CTCoreBundle:Home:index }

ct_core_view:
    path:    /film/{id}
    defaults: { _controller: CTCoreBundle:Film:view }
    requirements:
        id: \d+
ct_core_add:
    path:    /add
    defaults: { _controller: CTCoreBundle:Film:add }


