ct_core_home:
    path:     /
    defaults: { _controller: CTCoreBundle:Movie:index }

ct_core_view:
    path:    /film/{id}
    defaults: { _controller: CTCoreBundle:Movie:view }
    requirements:
        id: \d+

ct_core_edit:
    path:      /edit/{id}
    defaults:
        _controller: CTCoreBundle:Movie:edit
    requirements:
        id: \d+

ct_core_delete:
    path:      /delete/{id}
    defaults:
        _controller: CTCoreBundle:Movie:delete
    requirements:
        id: \d+