ct_core_home:
    path:     /
    defaults: { _controller: CTCoreBundle:Movie:index }

ct_core_view:
    path:    /film/{id}
    defaults: { _controller: CTCoreBundle:Movie:view }
    requirements:
        id: \d+

ct_core_edit:
    path:      /edit/{id}
    defaults:
        _controller: CTCoreBundle:Movie:edit
    requirements:
        id: \d+

ct_core_advancedsearch:
    path:      /advancedsearch
    defaults:
        _controller: CTCoreBundle:Movie:advancedSearch

ct_core_showlist:
    path: /showlist
    defaults:
       _controller: CTCoreBundle:Movie:showList

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }