services:
#    ct_core.example:
#        class: CT\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ct_core.twig.extension:
        class: CT\CoreBundle\Twig\CoreExtension
        tags:
            - { name: twig.extension }