<?php

namespace CT\CoreBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */

use Doctrine\ORM\EntityRepository;

class MovieRepository extends EntityRepository
{
    public function findMovieByParameters($data)

    {

        return $this
        ->createQueryBuilder('m')
        ->where('m.complexity BETWEEN :complexityMin AND :complexityMax')
        ->andWhere('m.violence BETWEEN :violenceMin AND :violenceMax')
        ->andWhere('m.specialEffects BETWEEN :specialEffectsMin AND :specialEffectsMax')
        ->andWhere('m.twist BETWEEN :twistMin AND :twistMax')
        ->andWhere('m.originality BETWEEN :originalityMin AND :originalityMax')
        ->andWhere('m.emotion BETWEEN :emotionMin AND :emotionMax')
        ->setParameters(array(

            'complexityMin' => ($data['complexity'] - 1),

            'complexityMax' => ($data['complexity'] + 1),

            'violenceMin' => ($data['violence'] - 1),

            'violenceMax' => ($data['violence'] + 1),

            'specialEffectsMin' => ($data['specialEffects'] - 1),

            'specialEffectsMax' => ($data['specialEffects'] + 1),

            'twistMin' => ($data['twist'] - 1),

            'twistMax' => ($data['twist'] + 1),

            'originalityMin' => ($data['originality'] - 1),

            'originalityMax' => ($data['originality'] + 1),

            'emotionMin' => ($data['emotion'] - 1),

            'emotionMax' => ($data['emotion'] + 1)
        ))
        ->getQuery()->getResult();
    }
}
